# Microsoft SQL Server Database Configuration
# To use MSSQL, run application with --spring.profiles.active=mssql or set spring.profiles.active=mssql in application.properties
app.current.agent.email=john.alex@apexrealty.com

spring.datasource.url=jdbc:sqlserver://localhost:12972;databaseName=ApartmentSalesDB;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123

# JPA / Hibernate Configuration for Microsoft SQL Server (preserve schema without modification)
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File Upload Configuration
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# Media Storage Configuration
app.upload.dir=uploads
